### ISSUE TITLE
Multiple redundant calculation in parallel running of serial examples

### ISSUE THREAD

**Issue by platipodium** [virgesmith/neworder#61]
When issueing, e.g., 

`mpirun -np 4 python examples/people/model.py`

the independent processors duplicate work:

```
[py 1/4] check OK: time=2051-01-01 size=329717 mean_age=41.77, pct_female=49.30 net_migration=1130.0 (20175-19045.0)
[py 3/4] check OK: time=2051-01-01 size=329717 mean_age=41.77, pct_female=49.30 net_migration=1130.0 (20175-19045.0)
[py 2/4] check OK: time=2051-01-01 size=329717 mean_age=41.77, pct_female=49.30 net_migration=1130.0 (20175-19045.0)
```

Is this intentional or is it just wasting CPU cycles?

**Comment by platipodium** [comment]
This is associated with [openjournals/joss-reviews#3351](https://github.com/openjournals/joss-reviews/issues/3351)

**Comment by virgesmith** [comment]
This particular example isn't set up to be (usefully) run in parallel - if you execute via `mpiexec` it will just do identical runs in each process, because the seeding strategy is set to `neworder.MonteCarlo.deterministic_identical_stream`. You can change the seeding strategy if you want different random streams for each process - if you haven't already seen it i'd recommend reading this page https://neworder.readthedocs.io/en/stable/tips/
